# Changement de variable sur simplex

In [30]:
#install.packages("SphericalCubature")
library("SphericalCubature")
help("rect2polar")

In [31]:
data<-read.csv("data_visco.csv")
data_lasso <- read.csv("data_lasso.csv")
data_AIC <- read.csv("data_AIC.csv")

Warning message in scan(file = file, what = what, sep = sep, quote = quote, dec = dec, :
“Fin de fichier (EOF) dans une chaîne de caractères entre guillements”


### Change of  variables from a simplex to a N-sphere with the N-sphere coordinates

In [32]:
change_in_phi_from_x = function(x){ #We put in argument a matrix or a vector that takes n values in a simplex
    epsilon<-1e-9  # We had a little noise to insure that we can devide by 0
    X<-as.matrix(x[, -1]/100)
    X[which(X == NaN)] <- 0.
    for (i in 1:dim(X)[1]){   #To ensure that we each row is equal to 1 to remove the noise in the column with the highest values in it
        X[ i,23] <- X[ i,23] - (sum(X[i, ]==0.))*epsilon
    }
    X[which(X == 0.)] <- epsilon
    Y<-sqrt(X) #We do a first change of variables y²=x eq y=sqrt(x)
    Y[is.na(Y)] <- 0  #If we have some Nan in our matrix we replace them by zeros
    return(t(as.matrix(rect2polar(t(Y))$phi)))
}



### Change of  variables from a N-sphere to an simplex with the N-sphere coordinates

In [33]:
change_in_x_from_phi = function(phi){ #We put in argumennt a matrix or a vector that takes n-1 values of angles in [0, pi/2]
    Phi<-as.matrix(phi)  
    r=rep(1,dim(Phi)[1])  #To realize our change of variables considered in the function polar2rect in R it needs to take a radius equals to 1 
    new<-(t(polar2rect(r, t(Phi))))**2  # We realize the change of variables such that f.e. x_1=cos²(theta_1)
    new[which(new<1e-4)]<-0   #We obtain sometimes values of order 1e-5 we replace it by 0
    return (new)
}


### Change of  variables from an simplex to an hypercube with the length ratio variables

In [34]:
change_in_lambda_from_x = function(x){  # We put in argument a matrix or a vector that takes n values in a simplex
    X<-as.matrix(x)
    Phi<-change_in_phi_from_x(X) #We change our variables from the simplex in angles in [0, pi/2 ]
    lambda<-(cos(Phi))**2 # We change of varaible is the following : lambda=cos(theta)
    return(lambda)
}

### Change of  variables from an hypercube to a simplex which the length ratio variables

In [35]:
change_in_x_from_lambda = function(lambda){ #We put in argument a matrix or a vector of n-1 variables in an hypercube
    Lambda<-as.matrix(lambda) 
    Phi<-acos(sqrt(Lambda)) #We change our variables from the hypercube to the N-spheres so n-1 angles in [0, pi/2]
    return(change_in_x_from_phi(Phi)) #We use the change of variables from a N-sphere to a simplex
}

## TESTS OF THE FUNCTIONS

### Test of the change of variables for the N-spheres coordinates

In [36]:
print(dim(data_lasso[, -1]))
print(data_lasso[1,-1 ]/100)
print(change_in_phi_from_x(data_lasso[1, ]))
print(change_in_x_from_phi(change_in_phi_from_x(data_lasso[1, ])))
print(sum(change_in_x_from_phi(change_in_phi_from_x(data_lasso[2, ]))))

[1] 7247   28
  X__3   X__4   X__8 X__10 X__17 X__18 X__29 X__30 X__43 X__48 X__49 X__53
1    0 0.0942 0.0852     0     0     0     0     0     0     0     0     0
  X__57 X__59 X__64 X__67 X__71  X__74 X__84 X__86 X__106 X__109 X__113 X__115
1     0     0     0     0     0 0.1367     0     0      0 0.6839      0      0
  X__117 X__133 X__138 autres
1      0      0      0      0


Warning message in sqrt(X):
“Production de NaN”


         [,1]     [,2]    [,3]     [,4]     [,5]     [,6]     [,7]     [,8]
[1,] 1.570765 1.258841 1.25908 1.570761 1.570761 1.570761 1.570761 1.570761
         [,9]    [,10]    [,11]    [,12]    [,13]    [,14]    [,15]    [,16]
[1,] 1.570761 1.570761 1.570761 1.570761 1.570761 1.570761 1.570761 1.570761
        [,17]    [,18]    [,19]    [,20]    [,21]        [,22]    [,23]
[1,] 1.570761 1.150371 1.570758 1.570758 1.570758 8.550445e-05 1.570796
        [,24]    [,25]     [,26]     [,27]
[1,] 1.107149 1.047198 0.9553166 0.7853982


Warning message in sqrt(X):
“Production de NaN”


     [,1]   [,2]   [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
[1,]    0 0.0942 0.0852    0    0    0    0    0    0     0     0     0     0
     [,14] [,15] [,16] [,17]  [,18] [,19] [,20] [,21]  [,22] [,23] [,24] [,25]
[1,]     0     0     0     0 0.1367     0     0     0 0.6839     0     0     0
     [,26] [,27] [,28]
[1,]     0     0     0


Warning message in sqrt(X):
“Production de NaN”


[1] 1


### Test of the change of variables for the length ratio

In [37]:
print(data_lasso[1:2,-1 ]/100)
print(change_in_lambda_from_x(data_lasso[1:2, ]))
print(change_in_x_from_lambda(change_in_lambda_from_x(data_lasso[1:2, ])))
print(sum(change_in_x_from_lambda(change_in_lambda_from_x(data_lasso[1:2, ]))))                             

  X__3   X__4   X__8 X__10 X__17 X__18 X__29 X__30 X__43 X__48 X__49 X__53
1    0 0.0942 0.0852     0     0     0     0     0     0     0     0     0
2    0 0.0942 0.0853     0     0     0     0     0     0     0     0     0
  X__57 X__59 X__64 X__67 X__71  X__74 X__84 X__86 X__106 X__109 X__113 X__115
1     0     0     0     0     0 0.1367     0     0      0 0.6839      0      0
2     0     0     0     0     0 0.1173     0     0      0 0.7032      0      0
  X__117 X__133 X__138 autres
1      0      0      0      0
2      0      0      0      0


Warning message in sqrt(X):
“Production de NaN”


      [,1]   [,2]      [,3]         [,4]         [,5]         [,6]         [,7]
[1,] 1e-09 0.0942 0.0940605 1.218620e-09 1.218620e-09 1.218620e-09 1.218620e-09
[2,] 1e-09 0.0942 0.0941709 1.218769e-09 1.218769e-09 1.218769e-09 1.218769e-09
             [,8]         [,9]        [,10]        [,11]        [,12]
[1,] 1.218620e-09 1.218620e-09 1.218620e-09 1.218620e-09 1.218621e-09
[2,] 1.218769e-09 1.218769e-09 1.218769e-09 1.218769e-09 1.218769e-09
            [,13]        [,14]        [,15]        [,16]        [,17]     [,18]
[1,] 1.218621e-09 1.218621e-09 1.218621e-09 1.218621e-09 1.218621e-09 0.1665854
[2,] 1.218769e-09 1.218769e-09 1.218769e-09 1.218769e-09 1.218769e-09 0.1429616
            [,19]        [,20]        [,21] [,22]        [,23] [,24] [,25]
[1,] 1.462202e-09 1.462202e-09 1.462202e-09     1 3.749399e-33   0.2  0.25
[2,] 1.422071e-09 1.422071e-09 1.422071e-09     1 3.749399e-33   0.2  0.25
         [,26] [,27]
[1,] 0.3333333   0.5
[2,] 0.3333333   0.5


Warning message in sqrt(X):
“Production de NaN”


     [,1]   [,2]   [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
[1,]    0 0.0942 0.0852    0    0    0    0    0    0     0     0     0     0
[2,]    0 0.0942 0.0853    0    0    0    0    0    0     0     0     0     0
     [,14] [,15] [,16] [,17]  [,18] [,19] [,20] [,21]  [,22] [,23] [,24] [,25]
[1,]     0     0     0     0 0.1367     0     0     0 0.6839     0     0     0
[2,]     0     0     0     0 0.1173     0     0     0 0.7032     0     0     0
     [,26] [,27] [,28]
[1,]     0     0     0
[2,]     0     0     0


Warning message in sqrt(X):
“Production de NaN”


[1] 2
